Making all scripts run within userdata, the init scripts do not run as intended. Adding the option to include an additional bucket access to IAM profile, fixing bind address for jenkins

diff --git a/jenkins.yml b/jenkins.yml
--- a/jenkins.yml
+++ b/jenkins.yml
@@ -24,6 +24,11 @@ Parameters:
     Default: ''
     Description: Enter a Existing Bucket Name to to use (Leave blank to create new)
 
+  AdditionalBucket:
+    Type: String
+    Default: ''
+    Description: Enter a Additional Bucket Name (if you want to use S3 IAM Profile Access for it)
+
 ###############################################################################
 # Jenkins Configuration
 ###############################################################################
@@ -257,6 +262,7 @@ Metadata:
         default: Redeploy/Existing Install Configuration
       Parameters:
         - ExistingBucketName
+        - AdditionalBucket
     -
       Label:
         default: Jenkins Configuration
@@ -323,6 +329,8 @@ Conditions:
   # Creates bucket if no existing name entered
   JenkinsBucketCon:
     !Equals [ !Ref ExistingBucketName, '' ]
+  AdditionalBucketCon:
+    !Equals [ !Ref AdditionalBucket, '' ]
 
 Mappings:
   RegionMap:
@@ -414,6 +422,23 @@ Resources:
           - Action: ec2:DescribeTags
             Effect: Allow
             Resource: "*"
+      Roles:
+        - !Ref InstanceRole
+
+  RolePolicies:
+    Type: AWS::IAM::Policy
+    Condition: AdditionalBucketCon
+    Properties:
+      PolicyName: !Sub ${AWS::StackName}-JenkinsServer-AdditionalBuckets-Policy
+      PolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+          # Allow all actions to one bucket (the supplied one, or the one you provided)
+          - Action: s3:*
+            Effect: Allow
+            Resource:
+              - !Sub arn:aws:s3:::${AdditionalBucket}
+              - !Sub arn:aws:s3:::${AdditionalBucket}/*
       Roles:
         - !Ref InstanceRole
 
@@ -576,6 +601,8 @@ Resources:
               export INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
               export STACKNAME='${AWS::StackName}'
               export HOSTNAME="${JenkinsSubdomain}.${HostedZone}"
+              export GITCLONE='${GitClone}'
+              export GITREPO="${!GITCLONE##*/}"
 
               ##########################################################
               # Install cfn bootstraping tools
@@ -618,7 +645,9 @@ Resources:
               # Jenkins User Add
               ##########################################################
 
-              useradd -d "/var/lib/jenkins" -m -s /bin/bash jenkins || error_exit "Failed to create Jenkins User"
+              if [ -z $(getent passwd jenkins) ]; then
+                useradd -d "/var/lib/jenkins" -m -s /bin/bash jenkins || error_exit "Failed to create Jenkins User"
+              fi
 
               ##########################################################
               # Add Jenkins Repo & Install
@@ -635,8 +664,8 @@ Resources:
               ## User war download to control version
               mkdir -p /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins || error_exit "Failed to create Jenkins directories"
               wget "http://mirrors.jenkins.io/war-stable/${JenkinsVersion}/jenkins.war" -qO /usr/share/jenkins/jenkins.war || error_exit "Failed to download Jenkins war"
-              chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins || error_exit "Failed to change Jenkins directory mode"
-              chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins || error_exit "Failed to change Jenkins directory owner"
+              chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Failed to change Jenkins directory mode"
+              chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Failed to change Jenkins directory owner"
 
               ##########################################################
               # Jenkins Log & Service Configuration
@@ -654,7 +683,7 @@ Resources:
               Group=jenkins
               Environment=JENKINS_HOME=/var/lib/jenkins
               ExecStartPre=/bin/rm -f /var/run/jenkins/jenkins.pid
-              ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --httpPort=8080 --httpListenAddress=127.0.0.1
+              ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --httpPort=8080 --httpListenAddress=0.0.0.0
               ExecReload=/bin/kill -s HUP $MAINPID
               TimeoutStartSec=0
               Restart=always
@@ -672,7 +701,11 @@ Resources:
               # Clone Script Repo
               ##########################################################
 
-              cd /root && git clone ${GitClone} || error_exit "Failed to Clone Scripts from Repo"
+              if [ ! -d "/root/${!GITREPO%.*}" ]; then
+                cd /root && git clone ${!GITCLONE} || error_exit "Failed to Clone Scripts from Repo"
+              else
+                cd /root/${!GITREPO%.*} && git pull
+              fi
 
               if [ '${GitBranch}' != 'master' ]; then
                 git checkout ${GitBranch} || error_exit "Failed to switch branches"
@@ -689,7 +722,7 @@ Resources:
               ## Swap Placeholders with Params
               ### Github Oauth Config Script
               sed -i 's/replaceClientID/${GithubClientID}/g' /root/cfn_jenkins/scripts/bootstrap/github_auth.groovy
-              sed -i 's/replaceClientSecret/${GithubClientSecret}/g' /root/cfn_jenkins/scripts/auth/github_auth.groovy
+              sed -i 's/replaceClientSecret/${GithubClientSecret}/g' /root/cfn_jenkins/scripts/bootstrap/github_auth.groovy
               sed -i 's/replaceGithubOrg/${GithubOrg}/g' /root/cfn_jenkins/scripts/bootstrap/github_auth.groovy
               sed -i 's/replaceGithubAdmins/${GithubAdmins}/g' /root/cfn_jenkins/scripts/bootstrap/github_auth.groovy
               ### Credentials Config Script
@@ -701,16 +734,18 @@ Resources:
               sed -i 's/replaceDomain/${HostedZone}/g' /root/cfn_jenkins/scripts/bootstrap/plugin_config.groovy
               sed -i 's/replaceDockerIP/${DOCKERIP}/g' /root/cfn_jenkins/scripts/bootstrap/plugin_config.groovy
               ### Mail Config
-              sed -i 's/replaceAdminEmail/${AdminEmail}/g' /root/cfn_jenkins/scripts/init/mail.groovy
-              sed -i 's/replaceMailUser/${MailUser}/g' /root/cfn_jenkins/scripts/init/mail.groovy
-              sed -i 's/replaceMailPassword/${MailPassword}/g' /root/cfn_jenkins/scripts/init/mail.groovy
-              sed -i 's/replaceMailHost/${MailHost}/g' /root/cfn_jenkins/scripts/init/mail.groovy
-              sed -i 's/replaceMailPort/${MailPort}/g' /root/cfn_jenkins/scripts/init/mail.groovy
-
-              mkdir -p /var/lib/jenkins/init.groovy.d || error_exit "Failed to Groovy Init Directory"
-              cp -rf /root/cfn_jenkins/scripts/init /var/lib/jenkins/init.groovy.d || error_exit "Failed to copy groovy init scripts"
+              sed -i 's/replaceAdminEmail/${AdminEmail}/g' /root/cfn_jenkins/scripts/bootstrap/mail.groovy
+              sed -i 's/replaceMailUser/${MailUser}/g' /root/cfn_jenkins/scripts/bootstrap/mail.groovy
+              sed -i 's/replaceMailPassword/${MailPassword}/g' /root/cfn_jenkins/scripts/bootstrap/mail.groovy
+              sed -i 's/replaceMailHost/${MailHost}/g' /root/cfn_jenkins/scripts/bootstrap/mail.groovy
+              sed -i 's/replaceMailPort/${MailPort}/g' /root/cfn_jenkins/scripts/bootstrap/mail.groovy
 
               systemctl start jenkins || error_exit "Failed to start Jenkins"
+
+              until $(curl --output /dev/null --silent --head --fail 127.0.0.1:8080/login); do
+                printf '.'
+                sleep 5
+              done
 
               INITIALPASSWORD=$(cat /var/lib/jenkins/secrets/initialAdminPassword)
 
@@ -722,9 +757,13 @@ Resources:
               done
 
               crumb=`curl "admin:${!INITIALPASSWORD}@127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)"`
-              curl --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/credentials.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Credentials Config"
-              curl --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/plugin_config.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Plugin Config"
-              curl --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/github_auth.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Github Oauth Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/plugins.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Plugins Install"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/executors.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Executors Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/security.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Security Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/mail.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Mail Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/credentials.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Credentials Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/plugin_config.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Plugin Config"
+              curl -H $crumb --data-urlencode "script=$(</root/cfn_jenkins/scripts/bootstrap/github_auth.groovy)" admin:${!INITIALPASSWORD}@127.0.0.1:8080/scriptText || error_exit "Failed to run Groovy Github Oauth Config"
               systemctl stop jenkins || error_exit "Failed to stop Jenkins"
 
               cat > '/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion' << EOF
@@ -735,7 +774,7 @@ Resources:
               ${JenkinsVersion}
               EOF
 
-              aws s3 sync /var/lib/jenkins/ s3://${BUCKET}/jenkins --exclude "*" --include "*.xml" --include "*.key" --include "secrets/*"
+              aws s3 sync /var/lib/jenkins/ s3://${BUCKET}/jenkins --exclude "*" --exclude "*/" --exclude ".jenkins" --include "*.xml" --include "*.key" --include "secrets/*"
 
               mkdir -p /var/lib/jenkins/data || error_exit "Failed to create Jenkins data directory"
 
@@ -873,7 +912,7 @@ Resources:
             apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || error_exit "Failed to add APT Repo Key"
             apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' || error_exit "Failed to add Repo List"
 
-            apt-get update && apt-get install docker-engine=${DockerVersion}-0* || error_exit "Failed to Install Docker Engine"
+            apt-get update && apt-get install -y docker-engine=${DockerVersion}-0* || error_exit "Failed to Install Docker Engine"
 
             ##########################################################
             # Docker Setup
@@ -888,7 +927,8 @@ Resources:
 
             [Service]
             Type=notify
-            ExecStart=/usr/bin/dockerd -H tcp://127.0.0.1:9800 -H unix:///var/run/docker.sock --pidfile=/var/run/docker.pid --tlsverify=false
+            Environment=DOCKER_CONTENT_TRUST=0
+            ExecStart=/usr/bin/dockerd -H tcp://127.0.0.1:9800 -H unix:///var/run/docker.sock --pidfile=/var/run/docker.pid
             ExecReload=/bin/kill -s HUP $MAINPID
             LimitNOFILE=infinity
             LimitNPROC=infinity
