Fixing warnings file. Fixing maste label set. Adding additional plugins. Adding additional log collections for sumologic. Changing logging options to be included inside systemd service file. adding logrotate config for jenkins log file. Adding wait checked for JJB seed job if ran. Adding custom properties file creation to be use in jobs (global variable work around

diff --git a/jenkins.yml b/jenkins.yml
--- a/jenkins.yml
+++ b/jenkins.yml
@@ -59,20 +59,6 @@ Parameters:
       - "2.7.1"
     Description: Choose Jenkins Version to Install
 
-  JenkinsLogLevel:
-    Type: String
-    Default: "INFO"
-    AllowedValues:
-      - "SEVERE"
-      - "WARNING"
-      - "INFO"
-      - "CONFIG"
-      - "FINE"
-      - "FINER"
-      - "FINEST"
-      - "ALL"
-    Description: Choose log level for Jenkins Master
-
   MasterInstanceType:
     Type: String
     Default: t2.micro
@@ -299,7 +285,6 @@ Metadata:
         - MasterInstanceType
         - JenkinsSubdomain
         - JenkinsVersion
-        - JenkinsLogLevel
         - JJBRepo
     -
       Label:
@@ -639,7 +624,7 @@ Resources:
               export DEBIAN_FRONTEND=noninteractive
               export INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
               export STACKNAME='${AWS::StackName}'
-              export HOSTNAME="${JenkinsSubdomain}.${HostedZone}"
+              export HOSTNAME="${JenkinsSubdomain}-master.${HostedZone}"
               export GITCLONE='${GitClone}'
               export GITREPO="${!GITCLONE##*/}"
               export JJBREPO='${JJBRepo}'
@@ -705,10 +690,11 @@ Resources:
               libxrender1 libxtst6 net-tools openjdk-8-jre-headless psmisc ucf x11-common || error_exit "Jenkins Install: Failed to install dependencies"
 
               ## User war download to control version
-              mkdir -p /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Jenkins Install: Failed to create Jenkins directories"
+              mkdir -p /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/lib/jenkins/logs || error_exit "Jenkins Install: Failed to create Jenkins directories"
               wget "http://mirrors.jenkins.io/war-stable/${JenkinsVersion}/jenkins.war" -qO /usr/share/jenkins/jenkins.war || error_exit "Jenkins Install: Failed to download Jenkins war"
-              chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Jenkins Install: Failed to change Jenkins directory mode"
-              chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Jenkins Install: Failed to change Jenkins directory owner"
+              chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/lib/jenkins/logs || error_exit "Jenkins Install: Failed to change Jenkins directory mode"
+              chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/lib/jenkins/logs || error_exit "Jenkins Install: Failed to change Jenkins directory owner"
+              ln -s /var/lib/jenkins/logs /var/log/jenkins || error_exit "Failed to symlink Jenkins Log Directory"
 
               ##########################################################
               # Jenkins Log & Service Configuration
@@ -725,8 +711,10 @@ Resources:
               User=jenkins
               Group=jenkins
               Environment=JENKINS_HOME=/var/lib/jenkins
-              ExecStartPre=/bin/rm -f /var/run/jenkins/jenkins.pid
-              ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --httpPort=8080 --httpListenAddress=0.0.0.0
+              Environment=JENKINS_WAR=/usr/share/jenkins/jenkins.war
+              Environment=JENKINS_LOGFILE=/var/log/jenkins/jenkins.log
+              Environment=JENKINS_PORT=8080
+              ExecStart=/usr/bin/java -Djava.awt.headless=true -jar $JENKINS_WAR -DJENKINS_HOME=$JENKINS_HOME --httpPort=$JENKINS_PORT --httpListenAddress=0.0.0.0 --logfile=$JENKINS_LOGFILE
               ExecReload=/bin/kill -s HUP $MAINPID
               TimeoutStartSec=0
               Restart=always
@@ -739,6 +727,20 @@ Resources:
               EOF
 
               systemctl enable jenkins || error_exit "Jenkins Install: Failed to enable Jenkins"
+
+              cat > '/etc/logrotate.d/jenkins' << 'EOF'
+              /var/log/jenkins/jenkins.log /var/log/jenkins/access_log {
+                  compress
+                  dateext
+                  maxage 365
+                  rotate 99
+                  size=+4096k
+                  notifempty
+                  missingok
+                  create 644
+                  copytruncate
+              }
+              EOF
 
               ##########################################################
               # Clone Script Repo
@@ -789,7 +791,6 @@ Resources:
               systemctl start jenkins || error_exit "Jenkins Bootstrap: Failed to start Jenkins"
 
               until $(curl --output /dev/null --silent --head --fail 127.0.0.1:8080/login); do
-                printf '.'
                 sleep 5
               done
 
@@ -804,8 +805,8 @@ Resources:
               ## Pull In Backup Data
               if [ -n ${ExistingBucketName} ] && [ ${RestoreBackup} == 'true' ]; then
                 aws s3 sync s3://${ExistingBucketName}/jenkins /var/lib/jenkins || error_exit "Jenkins Sync: Failed to sync existing data"
-                chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/enkins /var/log/jenkins || error_exit "Jenkins Install: Failed to change Jenkins directory mode"
-                chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins /var/log/jenkins || error_exit "Jenkins Install: Failed to change Jenkins directory owner"
+                chmod -R 755 /var/run/jenkins/ /var/lib/jenkins /usr/share/enkins || error_exit "Jenkins Install: Failed to change Jenkins directory mode"
+                chown -R jenkins:jenkins /var/run/jenkins/ /var/lib/jenkins /usr/share/jenkins || error_exit "Jenkins Install: Failed to change Jenkins directory owner"
                 if [ -f /var/lib/jenkins/github_bootstrap ]; then
                   ADMINCREDS='${GithubCreds}'
                 fi
@@ -817,7 +818,6 @@ Resources:
               sleep 5
 
               until $(curl --output /dev/null --silent --head --fail 127.0.0.1:8080/login); do
-                printf '.'
                 sleep 5
               done
 
@@ -830,7 +830,6 @@ Resources:
               fi
 
               until $(curl --output /dev/null --silent --head --fail 127.0.0.1:8080/login); do
-                printf '.'
                 sleep 5
               done
 
@@ -861,19 +860,17 @@ Resources:
               --include "*.key" \
               --include "*secrets/*"
 
-              mkdir -p /var/lib/jenkins/data || error_exit "Jenkins Bootstrap: Failed to create Jenkins data directory"
-
-              cat > '/var/lib/jenkins/data/log.properties' << EOF
-              handlers=java.util.logging.ConsoleHandler
-              jenkins.level=${JenkinsLogLevel}
-              java.util.logging.ConsoleHandler.level=${JenkinsLogLevel}
-              EOF
-
               cp -f /root/${!GITREPO%.*}/scripts/xml/* /var/lib/jenkins/ || error_exit "Jenkins Bootstrap: Failed to Copy XML files in place"
               cp -rf /root/${!GITREPO%.*}/scripts/jobs /var/lib/jenkins/ || error_exit "Jenkins Bootstrap: Failed to Copy JJB Seed/Sync job"
 
               chmod -R 755 /var/lib/jenkins || error_exit "Jenkins Bootstrap: Failed to change Jenkins directory mode"
               chown -R jenkins:jenkins /var/lib/jenkins || error_exit "Jenkins Bootstrap: Failed to change Jenkins directory owner"
+
+              cat > '/var/lib/jenkins/variables' << EOF
+              JENKINS_BUCKET='${BUCKET}'
+              STACKNAME="${!STACKNAME}"
+              MASTER_INSTANCE_ID="${!INSTANCE_ID}"
+              EOF
 
               systemctl start jenkins || error_exit "Jenkins Bootstrap: Failed to start Jenkins"
 
@@ -883,13 +880,22 @@ Resources:
 
               if [ -n "${JJBRepo}" ]; then
                 until $(curl --output /dev/null --silent --head --fail 127.0.0.1:8080/login); do
-                  printf '.'
                   sleep 5
                 done
 
                 crumb=$(curl --user "${!ADMINCREDS}" "127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)")
 
                 curl -H $crumb --user "${!ADMINCREDS}" -X POST "127.0.0.1:8080/job/jjb-sync/build?token=${!JJBTOKEN}" || error_exit "Failed to run JJB Sync Job"
+
+               # Wait for JJB Seed Job to start
+               until [ -f '/var/lib/jenkins/jobs/jjb-sync/builds/1/log' ]; do
+                sleep 5
+               done
+
+               # Wait for JJB Seed Job to Finish
+               until [ $(grep 'Finished: SUCCESS' /var/lib/jenkins/jobs/jjb-sync/builds/1/log) == 'Finished: SUCCESS' ]; do
+                sleep 5
+               done
               fi
 
               ##########################################################
@@ -918,7 +924,6 @@ Resources:
               # Reboot After Success for all updates made
               ##########################################################
 
-              apt-get update && apt-get -y upgrade
               reboot
 
             - { BUCKET: !If [ JenkinsBucketCon, !Ref JenkinsBucket, !Ref ExistingBucketName ], DOCKERIP: !GetAtt BuildInstance.PrivateIp }
